### ISSUE TITLE
When the CSS styling is static, prefer using classses

### ISSUE THREAD

**Issue by kostasx** [ssoc1KAdamidis/projectTeam#2]
https://github.com/ssoc1KAdamidis/projectTeam/blob/7eb158036e1d29da8a36dbab57635e701f414a7d/src/views/Dashboard.jsx#L15

In this case, the style applied to the `<Title>` element does not contain any dynamic values, therefore you can add a `className` and move the CSS to a `.css` file. Inline style (the object style in React) is reserved for styling that can accept values dynamically, e.g. via user input, props, state variables, etc.

```jsx
<Title style={{fontSize: "25px", fontStyle: "bold", fontFamily: 'Courier new', margin: "50px"}}>
```

Should be like this:

```jsx
<Title className="dashboard-title">
```

In a `.css` file:

```css
.dashboard-title {
  font-size: 25px;
  font-weight: bold; /* bold is available in font-weight NOT font-style */
  font-family: 'Courier new';
  margin: 50px;
}
```

Note that `font-style` does not support a value `bold`. Check the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style) for accepted values.
